// Generated by github.com/temporalio/temporal-aws-sdk-generator
// from github.com/aws/aws-sdk-go version 1.35.7
// Copyright (c) 2020 Temporal Technologies Inc.  All rights reserved.

package awsclients

import (
	"github.com/aws/aws-sdk-go/service/marketplacecommerceanalytics"
	"go.temporal.io/sdk/workflow"
)

type MarketplaceCommerceAnalyticsClient interface {
	GenerateDataSet(ctx workflow.Context, input *marketplacecommerceanalytics.GenerateDataSetInput) (*marketplacecommerceanalytics.GenerateDataSetOutput, error)
	GenerateDataSetAsync(ctx workflow.Context, input *marketplacecommerceanalytics.GenerateDataSetInput) *MarketplacecommerceanalyticsGenerateDataSetFuture

	StartSupportDataExport(ctx workflow.Context, input *marketplacecommerceanalytics.StartSupportDataExportInput) (*marketplacecommerceanalytics.StartSupportDataExportOutput, error)
	StartSupportDataExportAsync(ctx workflow.Context, input *marketplacecommerceanalytics.StartSupportDataExportInput) *MarketplacecommerceanalyticsStartSupportDataExportFuture
}

type MarketplaceCommerceAnalyticsStub struct{}

func NewMarketplaceCommerceAnalyticsStub() MarketplaceCommerceAnalyticsClient {
	return &MarketplaceCommerceAnalyticsStub{}
}

type MarketplacecommerceanalyticsGenerateDataSetFuture struct {
	Future workflow.Future
}

func (r *MarketplacecommerceanalyticsGenerateDataSetFuture) Get(ctx workflow.Context) (*marketplacecommerceanalytics.GenerateDataSetOutput, error) {
	var output marketplacecommerceanalytics.GenerateDataSetOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type MarketplacecommerceanalyticsStartSupportDataExportFuture struct {
	Future workflow.Future
}

func (r *MarketplacecommerceanalyticsStartSupportDataExportFuture) Get(ctx workflow.Context) (*marketplacecommerceanalytics.StartSupportDataExportOutput, error) {
	var output marketplacecommerceanalytics.StartSupportDataExportOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

func (a *MarketplaceCommerceAnalyticsStub) GenerateDataSet(ctx workflow.Context, input *marketplacecommerceanalytics.GenerateDataSetInput) (*marketplacecommerceanalytics.GenerateDataSetOutput, error) {
	var output marketplacecommerceanalytics.GenerateDataSetOutput
	err := workflow.ExecuteActivity(ctx, "aws.marketplacecommerceanalytics.GenerateDataSet", input).Get(ctx, &output)
	return &output, err
}

func (a *MarketplaceCommerceAnalyticsStub) GenerateDataSetAsync(ctx workflow.Context, input *marketplacecommerceanalytics.GenerateDataSetInput) *MarketplacecommerceanalyticsGenerateDataSetFuture {
	future := workflow.ExecuteActivity(ctx, "aws.marketplacecommerceanalytics.GenerateDataSet", input)
	return &MarketplacecommerceanalyticsGenerateDataSetFuture{Future: future}
}

func (a *MarketplaceCommerceAnalyticsStub) StartSupportDataExport(ctx workflow.Context, input *marketplacecommerceanalytics.StartSupportDataExportInput) (*marketplacecommerceanalytics.StartSupportDataExportOutput, error) {
	var output marketplacecommerceanalytics.StartSupportDataExportOutput
	err := workflow.ExecuteActivity(ctx, "aws.marketplacecommerceanalytics.StartSupportDataExport", input).Get(ctx, &output)
	return &output, err
}

func (a *MarketplaceCommerceAnalyticsStub) StartSupportDataExportAsync(ctx workflow.Context, input *marketplacecommerceanalytics.StartSupportDataExportInput) *MarketplacecommerceanalyticsStartSupportDataExportFuture {
	future := workflow.ExecuteActivity(ctx, "aws.marketplacecommerceanalytics.StartSupportDataExport", input)
	return &MarketplacecommerceanalyticsStartSupportDataExportFuture{Future: future}
}
